# Generated by Django 5.0.6 on 2024-06-23 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar3', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_product', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=10)),
                ('data_add', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
