# Generated by Django 5.0.6 on 2024-06-23 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seminar3', '0002_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_summ', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_order', models.DateTimeField(auto_now_add=True)),
                ('order_klient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seminar3.klient')),
                ('order_product', models.ManyToManyField(to='seminar3.product')),
            ],
        ),
    ]
