# Generated by Django 5.0.6 on 2024-06-17 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seminar2', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='price_summ',
            new_name='order_summ',
        ),
    ]
